### ISSUE TITLE
Document source_code in the README

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/TFB-Documentation#1]
X Post from TechEmpower/FrameworkBenchmarks#1176

> As mentioned in TechEmpower/FrameworkBenchmarks#1175, there's no explanation of source_code in the main readme. Here's a short one: The source_code file is used to count the lines of code in the project - each file listed in source_code has its lines counted and the result is include in results.json. TFB does not use the numbers in any of the graphs but we include them for other consumers of the data

**Comment by hamiltont** [comment]
> and the result is include in results.json

How about we change to something like this: 

> and the result is include in `results.json` under the `rawData` > `slocCounts` keys, as shown here:

```
  "rawData": {
    "slocCounts": {
      "mojolicious": 72, 
      "scruffy": 47, 
      "nodejs": 217, 
      "spring": 242, 
      "cpoll-cppsp": 82, 
      "slim": 1889, 
      "dropwizard": 293, 
      "revel": 258, 
      "dancer": 32, 
<snip>
```

Note that the keys used are framework names (e.g. `ringo`) and not he framework test names (e.g. `ringojs-raw`).

**Comment by hamiltont** [comment]
Perhaps alos mention we're using the `cloc` tool to provide this functionality
