### ISSUE TITLE
Installation guide issues

### ISSUE THREAD

**Issue by marko-asplund** [TechEmpower/TFB-Documentation#18]
I ran into a problem trying to set up TFB test environment by following the Installation-Guide.
This is a new server at travis-ci.com running Ubuntu 12.04.5 LTS.

Everything went fine until "Setting up prerequisites". One set of problems results from multiple Python installations being available in different paths. Python paths resolve as follows:
- root: `/usr/bin/python`, `/usr/local/bin/pip`
- normal user: `/opt/python/2.7.9/bin/python`, `/opt/python/2.7.9/bin/pip`

When I install Python modules with pip as root the modules aren't visible when running the `toolset/run-tests.py` script as normal user.

**Comment by marko-asplund** [comment]
This issue can be worked around by explicitly specifying python path as follows:
```/usr/bin/python toolset/run-tests.py --install database --install-only```

**Comment by hamiltont** [comment]
Perhaps we shoudl recommend some reading in the "prerequisites" section too - something like http://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/ is a great introductory text on pip usage

**Comment by marko-asplund** [comment]
about granting admin access: in my opinion it would be better to add users to the sudo group instead of adding user specific entries in /etc/sudoers file. users can then be added and removed from groups using the `usermod` command.

**Comment by marko-asplund** [comment]
regarding ssh key authentication setup: AFAIK, it's not good practice to generate a single public key pair and distribute it across all servers. IMO, the correct approach would be to generate separate key pairs per account on each server and then distribute public keys as needed.

**Comment by hamiltont** [comment]
> AFAIK, it's not good practice to generate a single public key pair and distribute it across all servers.

Agreed, it's not, but I suspect that's more than we want to cover in our startup guide. The goal is just to get people started, and not necessarily educate them on proper server security. I think a link to some extensive documentation might be the best approach here. 

Note that some of these docs will have to chagne if TechEmpower/FrameworkBenchmarks#1245 happens

**Comment by marko-asplund** [comment]
It would be nice to make setting up the environment easier for the curious newcomer developers who want to install on their own sandbox. A simple way would be to provide default values that would work out-of-the-box in this scenario e.g.:
```
export TFB_SERVER_USER=testrunner
export TFB_SERVER_HOST=127.0.0.1
export TFB_DATABASE_USER=techempower
export TFB_DATABASE_HOST=127.0.0.1
export TFB_CLIENT_USER=techempower
export TFB_CLIENT_HOST=127.0.0.1
```
the defaults should be consistent with the rest of the docs and default config files (e.g. `benchmark.cfg`).

It would also be good to test the installation document in a clean Ubuntu installation to ensure correctness and internal consistency.

**Comment by marko-asplund** [comment]
> ...
> Agreed, it's not, but I suspect that's more than we want to cover in our startup guide.

sure, I can understand that. perhaps there could be a quick mention of this in the docs.

**Comment by nbrady-techempower** [comment]
closing this. a few changes coming. i will be adding a quick startup script that does everything in the installation guide for users running a single instance setup
