### ISSUE TITLE
Clarify production environment

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/TFB-Documentation#22]
[This page](https://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Environment/index.html) lists the peak environment as ubuntu 12.04. I thought we were using 14.04 currently?

**Comment by LadyMozzarella** [comment]
Yes, you're right - that needs to be updated. We're using 14.04. I had originally copied it from the [environment details on the results site](https://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Environment/index.html), which hasn't been updated to reflect round 10 yet.
