### ISSUE TITLE
Deprecated mkdocs.yml Structure

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/TFB-Documentation#29]
Latest build is failing: https://readthedocs.org/builds/frameworkbenchmarks/2960689/ 

Looks like they're deprecating the structure we have for mkdocs.yml.

**Comment by andregmoeller** [comment]
mkdocs will generate a sitemap (http://www.sitemaps.org) for the respective site.
A sitemap consists of urls and each url includes a "loc" child entry. This entry is the
url of the page and must begin with the protocol and end with a trailing slash, if your web server requires it (see http://www.sitemaps.org/protocol.html#locdef).

mkdocs uses the site_url variable to generate the respective loc entries (see https://github.com/mkdocs/mkdocs/blob/3c6a66b38825dc409f1f8e000bd041f57ee225be/mkdocs/templates/sitemap.xml#L14) and therefore the site_url variable must either be empty or include a protocol.

So, possible solutions to fix this issue are
- setting site_url to http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/
- not setting the site_variable to any value
