### ISSUE TITLE
Quick start guide fails...

### ISSUE THREAD

**Issue by ryanlath** [TechEmpower/TFB-Documentation#44]
Following these instructions:
https://github.com/TechEmpower/FrameworkBenchmarks

Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-86-generic x86_64)

I need a  password?  Whaaaaa?

At these instructions:
toolset/run-tests.py --install server --mode verify --test beego

I get: 
`FWROOT is /home/vagrant/FrameworkBenchmarks
WARNING:root:results.json for test not found.
WARNING:root:Framework fasthttp does not define a default test in benchmark_config.json
WARNING:root:Framework fasthttp does not define a default test in benchmark_config.json
================================================================================
  Preparing Server, Database, and Client ...
================================================================================

bash: cpu0/cpufreq/scaling_governor: No such file or directory
bash: cpu1/cpufreq/scaling_governor: No such file or directory
vagrant@127.0.0.1's password:
`

**Comment by nbrady-techempower** [comment]
If it is prompting you for a password then you did not complete the instructions properly. The very first step here http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Installation-Guide/ removes the sudo passwd prompt. I have just recently followed these instructions.

**Comment by LadyMozzarella** [comment]
@nbrady-techempower @ryanlath is referring to the [readme on the main TFB project](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/README.md#quick-start-guide), which is supposed to use vagrant to get started quicker. I'm not sure when the last time was that someone went through that process. It should be revisited and updated if needed. I'm going to reopen this issue until someone can test that setup.

**Comment by cjnething** [comment]
Hi @ryanlath I once had this problem and it's because I missed this step: `cd ~/FrameworkBenchmarks. `
The steps I was following are located here: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Installation-Guide/?highlight=vagrant%20up
Although it's also on the quick start guide (it's easy to miss it, it's located in Step 5). 
Please let me know if that doesn't work and we can brainstorm another solution!

**Comment by nbrady-techempower** [comment]
good catch all! updated the readme as discussed https://github.com/TechEmpower/FrameworkBenchmarks/pull/2153
