### ISSUE TITLE
Extend the description of benchmark_config.json for contributors

### ISSUE THREAD

**Issue by zloster** [TechEmpower/TFB-Documentation#65]
Extend the description of `benchmark_config.json` and how it can be used to support various configuration permutations of given framework. Highlight the support of different setup scripts. The description seems to be [here](https://github.com/TechEmpower/TFB-Documentation/blob/master/docs/Codebase/Framework-Files.md).
 Some projects currently using this feature are:

- [undertow](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/undertow)
- [rapidoid](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/rapidoid)
- [servlet](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/servlet)
- [dropwizard](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/dropwizard)

The idea comes from discussion here: https://github.com/TechEmpower/FrameworkBenchmarks/pull/2678

**Comment by nbrady-techempower** [comment]
A more thorough explanation of the individual fields was done recently, and an update on how to utilize multiple dockerfiles is incoming
