### ISSUE TITLE
Documentation doesn't build

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/TFB-Documentation#80]
Use a Github webhook to build documentation. Github services were disabled.

https://developer.github.com/changes/2018-04-25-github-services-deprecation/
https://docs.readthedocs.io/en/latest/webhooks.html#webhook-github-services

**Comment by nbrady-techempower** [comment]
Closing re: documentation moved to https://github.com/TechEmpower/FrameworkBenchmarks/wiki
